---
title: "Comparing Env Data In Situ vs in the Lab"
author: "Hannah Merges"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```


## Load libraries 
```{r}
library(patchwork)
library(tidyverse)
library(here)
library(car)
library(GGally)
library(PNWColors)
library(seacarb)
library(broom)
library(agricolae)
library(lme4)
library(lmerTest)
library(modelsummary)
library(performance)
library(sjPlot)
library(broom)
library(purrr)
library(stringr)
library(emmeans)
library(MuMIn)
library(forcats)
library(ggmap)
library(maptools)
library(kriging)

```

## Bring in datasets
```{r}
AllChemData <- read_csv("https://raw.githubusercontent.com/njsilbiger/MooreaSGD_site-selection/main/Data/August2021/Allbiogeochemdata_QC.csv")
pH <- read_csv(here("Data", "pHSlope.csv")) 
WaterChem <- read_csv(here("Data", "2024_WaterChemMeasurements.csv"))
```

### view dfs and start tidying 
```{r}

### only view columns that are necessary 

AllChemData_edit <- AllChemData %>% 
  select(!c(lat, lon, Top_Plate_ID:DateTime, M_C:Lignin_Like)) %>% 
  group_by(CowTagID, Location) %>% 
  summarise(sal_avg = mean(Salinity), 
            temp_avg = mean(Temperature), 
            TA_avg = mean(TA), 
            pH_avg = mean(pH), 
            phos_avg = mean(Phosphate_umolL), 
            NN_avg = mean(NN_umolL), 
            silicate_avg= mean(Silicate_umolL), 
            ammonia_avg = mean(Ammonia_umolL)) %>% 
  filter(silicate_avg < 40) %>% 
  pivot_longer(cols = sal_avg:ammonia_avg, names_to = "EnvParams")


WaterChem_edit <- WaterChem %>% 
  select(!c(time:experiment_number, orion_pH:TrisCalDate, note)) %>% 
  drop_na(phosphate) %>% 
  group_by(treatment_level, Location, date) %>% 
  summarise(sal_avg = mean(salinity),
            TA_avg = mean(TA),
            phos_avg = mean(phosphate), 
            NN_avg = mean(NN), 
            silicate_avg= mean(silicate), 
            ammonia_avg = mean(ammonia)) %>% 
  pivot_longer(cols = sal_avg:ammonia_avg, names_to = "EnvParams")


```

#### Need to join the df in order to plot 
### currently visualizing the way to do this being my treatments/experimental nuts on x and natural gradient on y per parameter 
## and then put a abline=1 to see how the points compare 
```{r}
Measurements_to_Compare <- WaterChem_edit %>% 
  full_join(AllChemData_edit, join_by(Location, EnvParams, value))


```

## try some plots 
```{r}
## try to plot points against each other so can see side by side 
ComparingEnvData1 <- AllChemData_edit %>% 
  filter(Location=="Cabral") %>% 
  ggplot(aes(x=factor(CowTagID, level = c("C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14", "C15", "C16", "C17", "C18", "C19", "C20", "CSEEP")), 
             y=value)) +
  geom_col() + 
  facet_wrap(~EnvParams, scales = "free_y") +
  labs(x="Cabral")

ComparingEnvData1

ComparingEnvData2 <- AllChemData_edit %>% 
  filter(Location=="Varari") %>% 
  ggplot(aes(x=factor(CowTagID, level = c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10", "V11", "V12", "V13", "V14", "V15", "V16", "V17", "V18", "V19", "V20", "VSEEP")), 
             y=value)) +
  geom_col() + 
  facet_wrap(~EnvParams, scales = "free_y") + 
  labs(x= "Varari")

ComparingEnvData2

ComparingEnvData1 + ComparingEnvData2

ComparingEnvData3 <- WaterChem_edit %>% 
  filter(treatment_level!="Fresh", 
         EnvParams=="silicate_avg", 
         date!="1/14/24") %>% 
  ggplot(aes(x=factor(treatment_level, level=c("Ambient", "Low", "Medium", "High")),
             y=value)) + 
  geom_col() + 
  facet_wrap(date~EnvParams, scales = "free_y") + 
  labs(x="Treatment Levels")
ComparingEnvData3


####### 
# all next to each other 
ComparingEnvData1 + ComparingEnvData2 + ComparingEnvData3
```

















