---
title: "Experiment_Analysis_Thesis"
author: "Hannah Merges"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries 

```{r, echo=FALSE, message=FALSE}
library(patchwork)
library(tidyverse)
library(here)
library(PNWColors)
library(viridis)
library(car)
library(lubridate)
library(lme4)
library(lmerTest)
library(modelsummary)
#library(tidymodels)
#library(flextable)
library(performance)
library(agricolae)
library(broom)
library(stringr)
library(emmeans)
library(MuMIn)
library(betareg)
library(ggridges)
library(ggplot2)
library(viridis)
library(hrbrthemes)
```

## Load datasets 

```{r, echo=FALSE, message=FALSE}
SettlementCount_updated <- read_csv(here::here("Data", "SettlementCounts_edited.csv"))

SettlementCount_updated <- SettlementCount_updated %>% 
  filter(settled!=0) #%>% ##dropped one outlier in data where there were 0 counts for everything, so I think no larvae were actually added

### bring in settlement counts and water chem data to get salinity in addition to nutrients (found this file from script: )
SettlementCount_wsalinity <- read_csv(here::here("Data", "SettlementCounts_edited_wSALINITY.csv"))

SettlementCount_wsalinity <- SettlementCount_wsalinity %>% 
  filter(settled!=0)

```

## Tidy the data 
- adding in proportion of settlement calculations 
```{r}

SettlementCount_updated <- SettlementCount_updated %>% 
  dplyr::mutate(proportion_settled = settled/20)

SettlementCount_wsalinity <- SettlementCount_wsalinity %>% 
  dplyr::mutate(proportion_settled = settled/20)

#SettlementCount_wsalinity_andpH <- SettlementCount_wsalinity %>% 
  
SettlementCount_updated_Cabral <- SettlementCount_updated %>% 
  filter(site=="Cabral") #%>% 
  #summarize(meansettled = mean(settled), 
       #  sesettled = sd(meansettled) / sqrt(n()))

max(SettlementCount_updated_Cabral$proportion_settled)
min(SettlementCount_updated_Cabral$proportion_settled)
mean(SettlementCount_updated_Cabral$settled)
sd(SettlementCount_updated_Cabral$settled) / sqrt(length(SettlementCount_updated_Cabral$settled))


SettlementCount_updated_Varari <- SettlementCount_updated %>% 
  filter(site=="Varari")

max(SettlementCount_updated_Varari$proportion_settled)
min(SettlementCount_updated_Varari$proportion_settled)
mean(SettlementCount_updated_Varari$settled)
sd(SettlementCount_updated_Varari$settled) / sqrt(length(SettlementCount_updated_Varari$settled))


```


## Models for Thesis
-  Using silicate as the main predictor and using proportions as the response 
-  **Results:**  Varari is significant, Cabral is not 

```{r}

########################
## test to make sure there is no sig effect of treatment bin for either site 
## can then drop it from the model 
########################
treatment_bin <- lm(proportion_settled ~ treatment_level*treatmentID_rep, data = SettlementCount_updated %>% 
                       filter(site=="Cabral"))

anova(treatment_bin)
check_model(treatment_bin)

######################
## Varari 
######################

## does it look okay just logging ? if not, use beta regression

## regular lmer 
silicate_settlersV <- lmer(proportion_settled ~ silicate + (1|date), data = SettlementCount_updated %>% 
                       filter(site=="Varari"))

anova(silicate_settlersV)
summary(silicate_settlersV)
r.squaredGLMM(silicate_settlersV)
check_model(silicate_settlersV)

######################
## Cabral 
######################

silicate_settlersC <- lmer(proportion_settled ~ silicate + (1|date), data = SettlementCount_updated %>% 
                       filter(site=="Cabral"))

anova(silicate_settlersC)
summary(silicate_settlersC)
r.squaredGLMM(silicate_settlersC)
check_model(silicate_settlersC)


```

## Basic plots 

```{r}
######################
## Varari 
######################

V_settlersPlot <- SettlementCount_updated %>% 
  filter(site=="Varari") %>% 
  ggplot(aes(x=silicate, 
             y=settled)) + 
  coord_trans(y="log") +
  geom_point(size=4, aes(color=treatment_level)) + 
  geom_smooth(method="lm") + 
  theme_classic() 

V_settlersPlot

##
V_proportion_settlers <- SettlementCount_updated %>% 
  filter(site=="Varari") %>% 
  ggplot(aes(x=silicate, 
             y=proportion_settled)) + 
  coord_trans(y="log") +
  geom_point(size=4, aes(color=treatment_level)) + 
  geom_smooth(method="lm", formula='y~x', color="black") + 
  scale_color_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                    limits=c("Ambient", "Low", "Medium", "High"), 
                    guide="none") +
  theme_classic() + 
  coord_cartesian(ylim = c(0, 1)) + 
  labs(x = expression(Silicate~(mu*mol~L^-1)), 
       y = "Proportion of Settlers", 
       color= "Date") + 
  theme(axis.text.x=element_text(size=20), 
        axis.text.y=element_text(size=20), 
        axis.title.x=element_text(size=20), 
        axis.title.y=element_text(size=20), 
        legend.text=element_text(size=20),  # Adjust legend text size
        legend.title=element_text(size=20), # Adjust legend title size
        strip.text=element_text(size=20))

V_proportion_settlers
ggsave(here::here("Outputs","SettlementExperiment", "Thesis_Figures", "V_settlerprop.jpg"), 
       width=10, height=7)


######################
## Cabral 
######################

C_settlersPlot <- SettlementCount_updated %>% 
  filter(site=="Cabral") %>% 
  ggplot(aes(x=silicate, 
             y=settled)) + 
  coord_trans(y="log") +
  geom_point() + 
  geom_smooth(method="lm")

C_settlersPlot

##
C_settler_prop <- SettlementCount_updated %>% 
  filter(site=="Cabral") %>% 
  ggplot(aes(x=silicate, 
             y=proportion_settled)) + 
  coord_trans(y="log") +
  geom_point(size=4, 
             aes(color=treatment_level)) +
  scale_color_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                    limits=c("Ambient", "Low", "Medium", "High"), 
                    guide="none") +
 # geom_smooth(method="lm", formula='y~x', se=FALSE) + 
  theme_classic() + 
  coord_cartesian(ylim = c(0, 1)) + 
  labs(x = expression(Silicate~(mu*mol~L^-1)), 
       y = "Proportion of Settlers", 
       color= "Date") + 
  theme(axis.text.x=element_text(size=20), 
        axis.text.y=element_text(size=20), 
        axis.title.x=element_text(size=20), 
        axis.title.y=element_text(size=20), 
        legend.text=element_text(size=20),  # Adjust legend text size
        legend.title=element_text(size=20), # Adjust legend title size
        strip.text=element_text(size=20))

C_settler_prop
ggsave(here::here("Outputs","SettlementExperiment", "Thesis_Figures", "C_settlerprop.jpg"), 
       width=10, height=7)



C_settler_prop + V_proportion_settlers
ggsave(here::here("Outputs","SettlementExperiment", "Thesis_Figures", "settlerprop_bothsites.jpg"), 
       width=14, height=7)
```

#### Test models with salinity 

```{r}
SettlementCount_wsalinityV <- SettlementCount_wsalinity %>% 
  filter(site=="Varari")

max(SettlementCount_wsalinityV$salinity)
min(SettlementCount_wsalinityV$salinity)



######################
## using salinity 
######################

#### Cabral 

salinity_settlersC <- lmer(log(proportion_settled+1) ~ salinity + (1|date), data = SettlementCount_wsalinity %>% 
                       filter(site=="Cabral"))

anova(salinity_settlersC)

#### Varari 
salinity_settlersV <- lmer(log(proportion_settled+1) ~ salinity + (1|date), data = SettlementCount_wsalinity %>% 
                       filter(site=="Varari"))

anova(salinity_settlersV)
```










# Experimental Testing (can ignore)

## Boxplot with jitter 

```{r}
boxplot_silic <- SettlementCount_updated %>%
  ggplot(aes(x=silicate, 
             y=settled, 
             fill=site)) +
  geom_boxplot() +
  geom_jitter(aes(color=treatment_level)) +
  facet_wrap(~site) + 
  scale_fill_manual(values=c("lightgray", "lightgray")) + 
  scale_color_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                    limits=c("Ambient", "Low", "Medium", "High")) +
  theme_classic()


boxplot_silic

```


## Violin plot 

```{r}

##########################
## basic violin plot - silicate x 
##########################

violin1_silic <- SettlementCount_updated %>%
  ggplot(aes(x=silicate, 
             y=settled, 
             fill=site)) +
  geom_violin(width=1.4) +
  #geom_boxplot(width=0.1, color="grey", alpha=0.2) +
#  geom_jitter(aes(color=treatment_level)) +
  facet_wrap(~site) + 
 # scale_fill_manual(values=c("lightgray", "lightgray")) + 
 # scale_color_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                   # limits=c("Ambient", "Low", "Medium", "High")) +
  theme_classic()


violin1_silic

##########################
## basic violin plot - treatment groups on x 
##########################

violin2_silic <- SettlementCount_updated %>%
  ggplot(aes(x=treatment_level,
             y=settled, 
             fill=treatment_level)) +
  geom_violin(width=1.4) +
  #geom_boxplot(width=0.1, color="grey", alpha=0.2) +
#  geom_jitter(aes(color=treatment_level)) +
  facet_wrap(~site) + 
 # scale_fill_manual(values=c("lightgray", "lightgray")) + 
  scale_fill_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                    limits=c("Ambient", "Low", "Medium", "High")) +
  scale_x_discrete(limits=c("Ambient", "Low", "Medium", "High")) +
  theme_classic()

violin2_silic


##########################
## violin plot with boxplot - treatment groups on x 
##########################

violin3_silic <- SettlementCount_updated %>%
  ggplot(aes(x=treatment_level, 
             y=settled, 
             fill=treatment_level)) +
  geom_violin(width=1.4) +
  geom_boxplot(width=0.4, color="black", alpha=0.2) +
  #geom_jitter(aes(color="black")) +
  facet_wrap(~site) + 
 # scale_fill_manual(values=c("lightgray", "lightgray")) + 
  scale_fill_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                    limits=c("Ambient", "Low", "Medium", "High")) +
  scale_x_discrete(limits=c("Ambient", "Low", "Medium", "High")) +
  theme_classic() + 
  labs(x="SGD Treatment", 
       y= "Number of Settled Larvae")

violin3_silic

##########################
## violin plot - silicate x and boxplot
##########################

violin4_silic <- SettlementCount_updated %>%
  ggplot(aes(x=silicate, 
             y=settled, 
             fill=treatment_level)) +
  geom_violin(width=1.4) +
 # geom_boxplot(width=0.4, color="black", alpha=0.2) +
  #geom_jitter(aes(color="black")) +
  facet_wrap(~site, scales="free_x") + 
 # scale_fill_manual(values=c("lightgray", "lightgray")) + 
  scale_fill_manual(values=c("deepskyblue", "darkseagreen", "darkgoldenrod3", "coral3"), 
                    limits=c("Ambient", "Low", "Medium", "High")) +
  #scale_x_discrete(limits=c("Ambient", "Low", "Medium", "High")) +
  theme_classic() + 
  labs(x = expression(Silicate~(mu*mol~L^-1)), 
       y= "Number of Settled Larvae", 
       fill= "Treatment Level") + 
  theme(axis.text.x=element_text(size=20), 
        axis.text.y=element_text(size=20), 
        axis.title.x=element_text(size=20), 
        axis.title.y=element_text(size=20), 
        legend.text=element_text(size=20),  # Adjust legend text size
        legend.title=element_text(size=20), # Adjust legend title size
        strip.text=element_text(size=20))   # Adjust facet label size
#  geom_signif(comparisons = SettlementCount_updated$silicate,   
           #   map_signif_level=TRUE)

violin4_silic
ggsave(here::here("Outputs","SettlementExperiment","Thesis_Figures","Exp_ViolinPlot.jpg"), 
       width=11, height =7)

```

## Models 

```{r}

######################
## using silicate 
######################

silicate_modelV <- lmer(log(settled+1) ~ silicate + (1|date), data = SettlementCount_updated %>% 
                       filter(site=="Cabral"))

anova(silicate_modelV)
summary(silicate_modelV)
r.squaredGLMM(silicate_modelV)
plot(silicate_modelV)


## plot

V_settlers <- SettlementCount_updated %>% 
  filter(site=="Varari") %>% 
  ggplot(aes(x=silicate, 
             y=settled)) + 
  coord_trans(y="log") +
  geom_point() + 
  geom_smooth(method="lm")
V_settlers

##########################
silicate_modelC <- lm(log(settled+1) ~ silicate, data = SettlementCount_updated %>% 
                       filter(site=="Cabral"))

anova(silicate_modelC)
summary(silicate_modelC)
r.squaredGLMM(silicate_modelC)
plot(silicate_modelC)


######################
## using treatments 
######################

treatment_modelV <- lm(settled ~ treatment_level, data = SettlementCount_updated %>% 
                       filter(site=="Varari"))

anova(treatment_modelV)
summary(treatment_modelV)
r.squaredGLMM(treatment_modelV)
check_model(treatment_modelV)

emmeans(treatment_modelV, pairwise~"treatment_level", adjust="Tukey")

treatment_modelC <- lm(settled ~ treatment_level, data = SettlementCount_updated %>% 
                       filter(site=="Cabral"))

anova(treatment_modelC)
summary(treatment_modelC)
r.squaredGLMM(treatment_modelC)
check_model(treatment_modelC)

emmeans(treatment_modelC, pairwise~"treatment_level", adjust="Tukey")


```






