## Try a kriging plot 
Do kriging plot with number of recruits on tiles along percent cover of certain habitat - do live coral vs sand vs dead coral vs rubble for rn 
```{r}
#####################################
## first part is mapping
####################################


# mean lat and long for the maps
MeanGPS<-latlong %>%
  group_by(Location) %>%
  summarise(lon = median(lon, na.rm = TRUE) + 0.0002, # add 0.0002 to fit all on map at zoom 19
            lat = median(lat, na.rm = TRUE))
SiteGPS<-latlong %>%
  group_by(Location, CowTagID) %>%
  summarise(lon = mean(lon, na.rm = TRUE),
            lat = mean(lat, na.rm = TRUE))

# Base Maps
VarariBaseMap<-get_map(MeanGPS %>%
                         filter(Location == "Varari") %>%
                         select(lon,lat),
                       maptype = 'satellite', zoom = 19)
CabralBaseMap<-get_map(MeanGPS %>%
                         filter(Location == "Cabral") %>%
                         select(lon,lat),
                       maptype = 'satellite', zoom = 18)


### Make a spatial kriging file with polygon layers ####
### Bring in the polygons for the sites
#Varari
V_kml <- getKMLcoordinates(kmlfile=here("Data","Polygons","Varari_Polygon.kml"), ignoreAltitude=T)
#Cabral
C_kml <- getKMLcoordinates(kmlfile=here("Data","Polygons","Cabral_Polygon.kml"), ignoreAltitude=T)

```

```{r}
### IF USING RANGES
# Get the data ranges for all variables to cleaner plots
# DataRange <-AllChemData %>%
#   filter(Plate_Seep == "Plate") %>%
#   select(-Temperature)%>%
#   group_by(Location) %>%
#   summarise_if(is.numeric, range, na.rm = TRUE) %>%
#   ungroup() %>%
#   mutate(min_max = c("min","max","min","max")) %>%
#   pivot_longer(cols = Salinity:Ammonia_umolL, names_to = "Parameters", values_to = "Values") %>%
#   pivot_wider(names_from = min_max, values_from = Values) %>%
#   select(Location, Parameters, min, max)
# mins<-DataRange %>%
#   filter(is.na(max)) %>%
#   select(-max)
#
# maxs<-DataRange %>%
#   filter(is.na(min)) %>%
#   select(-min)
#
# min_max<-left_join(mins,maxs)

```

```{r}
# pivot data to long form
nData <- latlong %>%
  pivot_longer(cols = 11:18, names_to = "Parameters", values_to = "Values")

# make a function to do all the krigings
Krig_function <-function(dat_in = data, Lat = "lat", Lon = "lon", Param = "Values", poly ) {

  dat <- dat_in[,c(Lon, Lat, Param)]
  names(dat) <- c('Lon', 'Lat', 'Param')


  dat<-dat%>%
    drop_na()

  x <- dat$Lon
  y <- dat$Lat
  z <-dat$Param

  krig1 <- kriging(x, y, z, pixels=500, polygons=poly, lags = 3) ###pixels controls how fine or course you want the prediction data frame to be
  krig2 <- krig1$map

return(krig2)
}

#temporary code
# a <- nData %>%
#   filter(Location == "Varari") %>%
#   filter(Parameters == 'Silicate_umolL') %>%
#   group_nest(Parameters) %>%
#   #select(lat, lon, Values) %>%
#   kriging(x = 'lon', y = 'lat', response = 'Values', polygons = V_kml) #, pixels = 500, lags = 3)
# a$map


# And do it "safely": skipping NAs without breaking the code
Krig_function_safe<-safely(Krig_function)
```



```{r}
# nest by all parameters to make it easy to plot all types of maps
# Varari
Varari_kriging <- nData %>%
  filter(Location == "Varari") %>%
  filter(CowTagID != "VSEEP") %>% # only plate data because seep skeps the maps
#   select(-Temperature)%>% # this is temporary until we get the temperature data entered
#   filter(Plate_Seep == "Plate", # only plot the plates because the seep samples skew the maps
#          Location == "Varari") %>%
  droplevels()%>%
#   pivot_longer(cols = Salinity:Ammonia_umolL, names_to = "Parameters", values_to = "Values") %>%
#   select(lat, lon, Tide, Day_Night, Date, Parameters, Values) %>% # select the values that are important for the kriging
#  group_nest(Tide, Day_Night, Date, Parameters) %>% # group by parameters
  select(-c(Location,CowTagID)) %>%
  group_nest(Parameters) %>% # group by parameters
  mutate(preds = map(data, ~Krig_function_safe(dat_in = .x, poly = V_kml)), # run the function for every nested group (i.e., Parameter)
      #   preds = map(preds, head, -1), # remove the error column
       #  preds = map(preds, flatten_df), # flatten back to a tibble
 # mutate(preds = unlist(preds))
         longname = Parameters,
         plots = map2(preds, longname, ~ggmap(VarariBaseMap)+ # map2 maps over multiple inputs simultaneously, in parallel
                        geom_point(data=.x$result, aes(x=x, y=y, colour=pred), size=4, alpha=0.5) +
                        geom_point(data = SiteGPS %>% filter(Location == 'Varari'), aes(x=lon, y=lat))+
                        scale_color_viridis_c(" ", option = "plasma") +
                        coord_sf() +
                        theme(axis.line=element_blank(),
                              axis.text.x=element_blank(),
                              axis.text.y=element_blank(),
                              axis.ticks=element_blank(),
                              axis.title.x=element_blank(),
                              axis.title.y=element_blank(),
                              panel.grid.major = element_line(color = 'white', linetype = "dashed",size = 0.5),
                              plot.background=element_rect(fill='white')) +
                        ggtitle(glue("Varari: {.y}"))))
```








## STATS TESTS - USE A LOGISTIC REGRESSION 
```{r}
## need to tidy the data for this first 
# change the total counts to all corals and then alive or dead --> how? 
# need to add comm comp data 

# for sand community 
model1 <- glm(Dead_Alive ~ Sand, family = binomial(link="logit"), data=RecruitmentCounts)
Anova(model1)

# for coral community 
model2 <- glm(Dead_Alive ~ Live_Coral, family = binomial(link="logit"), data=RecruitmentCounts)
Anova(model2)

# for dead coral community 
model3 <- glm(Dead_Alive ~ Dead_Coral, family = binomial(link="logit"), data=RecruitmentCounts)
Anova(model3)


# for rubble community 
model4 <- glm(Dead_Alive ~ Rubble, family = binomial(link="logit"), data=RecruitmentCounts)
Anova(model4)





```

## after models are run, want to get R2 values for them 

```{r}
# We'd also like to get a pseudo R^2 value that tells us how much of the variance in settler death/life is explained by the comm

pR2(model1) # gives pseudo R^2
# The last three columns are all different types of pseudo-R^2s --> usually use McFadden's rho-square


```


## plot the data from the models 
```{r}
plot(RecruitmentCounts$Sand, RecruitmentCounts$Dead_Alive,
     xlab="Community Composition of Sand, etc ",
     ylab="Probability of Settler Alive or Dead")
curve(predict(model1,data.frame(Sand=x),type="resp"),add=TRUE) # draws a curve based on prediction from logistic regression model

# Here's some code for making a nicer plot with ggplot
to.predict <- data.frame(Sand=seq(5,65,5))
predicted.data <- cbind(to.predict, as.data.frame(predict(model1, newdata=to.predict, type="response", se=TRUE)))

predicted.data

ggplot(lizards, aes(x=PA_ratio, y=Present)) +
  geom_point() +
  geom_line(data = predicted.data, aes(x=PA_ratio, y=fit), color="blue") +
  labs(x="Perimeter:Area Ratio", y="Presence of Lizards")
  theme_bw() 
```


